on:
  workflow_dispatch

jobs:
  test:
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
    - name: fail
      run: exit 1

  pass:
    runs-on: ubuntu-latest
    steps:
    - name: pass
      run: exit 0